# fly.toml app configuration file generated for new-api-q-htpg on 2026-03-24T00:14:13Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'new-api-q-htpg'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
